/**
 * Deterministic mockup compositing.
 *
 * The naive version of "show the logo on a bottle" asks the image model to
 * paint the logo into a new scene, and the model cannot do it faithfully:
 * lettering warps, marks drift, and every mockup shows a slightly different
 * logo. The one thing the person is looking at is their logo.
 *
 * So the scenes are photographs generated once at build time (committed under
 * public/mockups, regenerated by scripts/generate-mockup-scenes.mjs), each
 * with a placement zone measured against the actual image, and sharp places
 * the exact logo PNG into the zone. Pixel-identical logo in every mockup,
 * no per-mockup API cost, and a run renders in well under a second.
 *
 * Zones are flat affine placements on purpose: every scene was prompted
 * straight-on so that "resize and put it there" looks right. If the scenes
 * are ever regenerated, these numbers must be re-measured; the script's
 * header says the same from its side.
 */
import { readFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import { dominantColor } from "@/lib/brand/color";

interface Zone {
  /** What the board calls it. */
  title: string;
  /** File under public/mockups, without extension. */
  scene: string;
  left: number;
  top: number;
  width: number;
  height: number;
  /**
   * multiply lets the scene's own shading show through the logo, which is
   * what makes a flat PNG read as printed-on rather than stickered-on. It is
   * also what makes white backgrounds vanish when the generator could not
   * produce transparency: white times the scene is the scene.
   */
  blend: "multiply" | "over";
}

/** Measured against the committed 1024x1024 scenes. */
export const ZONES: Zone[] = [
  { title: "Bottle", scene: "bottle", left: 410, top: 505, width: 210, height: 230, blend: "multiply" },
  { title: "Coffee cup", scene: "cup", left: 387, top: 450, width: 250, height: 250, blend: "multiply" },
  { title: "Tote bag", scene: "tote", left: 387, top: 530, width: 250, height: 250, blend: "multiply" },
  { title: "Business card", scene: "card", left: 402, top: 425, width: 220, height: 180, blend: "multiply" },
  { title: "Storefront", scene: "storefront", left: 362, top: 65, width: 300, height: 200, blend: "multiply" },
];

function scenePath(scene: string): string {
  return path.join(process.cwd(), "public", "mockups", `${scene}.png`);
}

export interface Mockup {
  title: string;
  png: Buffer;
}

/**
 * The logo placed into every scene. The logo is contain-fitted into each
 * zone, so any aspect ratio lands unsquashed.
 */
export async function composeMockups(logoPng: Buffer): Promise<Mockup[]> {
  const mockups: Mockup[] = [];

  for (const zone of ZONES) {
    const scene = await readFile(scenePath(zone.scene));

    const fitted = await sharp(logoPng)
      .resize(zone.width, zone.height, {
        fit: "contain",
        background: { r: 255, g: 255, b: 255, alpha: 0 },
      })
      .png()
      .toBuffer();

    const png = await sharp(scene)
      .composite([{ input: fitted, left: zone.left, top: zone.top, blend: zone.blend }])
      .png()
      .toBuffer();

    mockups.push({ title: zone.title, png });
  }

  return mockups;
}

/**
 * The logo's dominant brand colour, as a hex string. Decoding happens here
 * because it needs sharp; the counting itself is pure and lives with the
 * colour maths. Downscaling to 64px first makes the count cheap and doubles
 * as noise reduction.
 */
export async function extractLogoColor(logoPng: Buffer): Promise<string | null> {
  const { data } = await sharp(logoPng)
    .resize(64, 64, { fit: "inside" })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  return dominantColor(data);
}

/**
 * A palette strip image: one swatch per colour with its hex printed under it.
 * Markdown cannot show a colour, so the board's palette is rendered as an
 * image, via SVG because that is the one input sharp rasterises for free.
 */
export async function paletteStripPng(hexes: string[]): Promise<Buffer> {
  const swatch = 160;
  const height = 200;
  const width = swatch * hexes.length;

  const cells = hexes
    .map((hex, i) => {
      const x = i * swatch;
      const label = hex.toUpperCase();
      return [
        `<rect x="${x}" y="0" width="${swatch}" height="150" fill="${hex}"/>`,
        `<text x="${x + swatch / 2}" y="180" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-size="20" fill="#333333">${label}</text>`,
      ].join("");
    })
    .join("");

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><rect width="${width}" height="${height}" fill="#ffffff"/>${cells}</svg>`;

  return sharp(Buffer.from(svg)).png().toBuffer();
}
